### ISSUE TITLE
Would you consider adding Typescript type definitions?

### ISSUE THREAD

**Issue by artis3n** [m0rtadelo/recursive-readdir-async#15]
I saw #7 adding support for ES6 modules, which is convenient. I currently use this library in a Typescript project via

```js
import { list as rraList } from 'recursive-readdir-async';
```

Typescript throws a compilation error (that I have to ignore) saying:

```
TS7016: Could not find a declaration file for module 'recursive-readdir-async'. '/<redacted>/node_modules/recursive-readdir-async/build/module.cjs.js' implicitly has an 'any' type.   Try `npm install @types/recursive-readdir-async` if it exists or add a new declaration (.d.ts) file containing `declare module 'recursive-readdir-async';`
```

I am not super familiar on how to do that myself, but I see many projects have type definitions under `@types`. The documentation for that appears to be <https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#publish-to-types>. [This page](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) also has some documentation on how to build in typescript types natively to your library.

Is this something you'd consider doing? Would be a convenience when using this library with typescript. I currently suppress the error with:

```ts
// @ts-ignore
import { list as rraList } from 'recursive-readdir-async';
```

**Comment by m0rtadelo** [comment]
I will add @types to avoid TypeScript errors as soon as possible. Thank you for your feedback!

**Comment by artis3n** [comment]
FWIW here are the types I created for my use of the `list` function's output, where `list` returns a `DiscoveredFilesResult` and is invoked as:

```ts
return await rraList(dirPath, options);
```

types:

```ts
export type DiscoveredFilesResult = Array<FileDiscoveredItem> | Array<RecursiveReaddirSysError> | Array<RecursiveReaddirFileError>;

export interface FileDiscoveredItem {
  name: string;
  path: string;
  fullname: string;
  isDirectory: boolean;
}

export interface RecursiveReaddirSysError {
  error: {
    message: string;
    errno: number;
    code: string;
    syscall: string;
    path: string;
  };
  path: string;
}

export interface RecursiveReaddirFileError {
  name: string;
  title: string;
  path: string;
  fullname: string;
  error: object;
}
```

Had to define this function as well to get Typescript to realize when the result is not an error:

```ts
function isFileDiscoveredItemArray(
  item: DiscoveredFilesResult
): item is Array<FileDiscoveredItem> {
  return !("error" in item[0]);
}
```

which comes from <https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards>.

**Comment by artis3n** [comment]
@m0rtadelo Are you still planning on doing this? I hit a `undefined` result issue that I am pretty sure would be prevented if the types I defined for this library were accurate :D

**Comment by m0rtadelo** [comment]
Hello.
Sorry i am a little busy and can't work on this now. MR's will be accepted.

Missatge de Ari Kalfus <notifications@github.com> del dia dv., 15 de gen.
2021 a les 19:21:

**Comment by artis3n** [comment]
That is fair!

**Comment by m0rtadelo** [comment]
Version 1.2.0 has been written totally in typescript and works with types in typescript projects as expected. Sorry for the wait
