### ISSUE TITLE
How use options include

### ISSUE THREAD

**Issue by KimNowakowski** [m0rtadelo/recursive-readdir-async#16]
Hello,

I had in options.include ['.xml'] for get only files with extension '.xml' but not working for me.
I get all files, but in exclude ['.xml'] all xml files not listed ?

const options = {
            mode: rra.LIST,
            recursive: true,
            stats: false,
            ignoreFolders: true,
            extensions: true,
            deep: false,
            realPath: true,
            normalizePath: true,
            include: ['.xml'],
            exclude: [],
            readContent: false,
            encoding: 'base64'
        }

Where is my mistake ?

Thanks.

Best Regards

**Comment by m0rtadelo** [comment]
Should work if the case are correct. Try to use the callback to delete the items, exemple:
```javascript
const result = await rra.list('.', options, function (obj, index, total) {
    console.log(`${index} of ${total} ${obj.path}`)
    return obj.name.toLowerCase().includes('.xml');
})
```
