### ISSUE TITLE
Rename result objec keys and add another custom keys

### ISSUE THREAD

**Issue by baur** [m0rtadelo/recursive-readdir-async#23]
Hi, 
First of all, nice work 👍, thank you!

I'd like to rename object keys, because of some components needs some specific names. 
I'm using the next solution, but it would be nice to have a native way 

```JS
const replaceKeysDeep = (obj, keysMap) => { 
    return _.transform(obj, function (result, value, key) { 
        var currentKey = keysMap[key] || key; 
        result[currentKey] = _.isObject(value) ? replaceKeysDeep(value, keysMap) : value; 
        inner function - replaceKeys
    });
}
```

```JS
const keysMap = {
                path: 'filepath',
                content: 'children'
            };
const result = replaceKeysDeep(tree, keysMap);
```

also, I'd like to add custom keys, for example `isOpen`, `isChecked` which uses some components

**Comment by m0rtadelo** [comment]
Hi,

sorry but as a TypeScript project properties types are predefined into Interfaces. I cannot add this feature in this project.
