### ISSUE TITLE
special character compatibility

### ISSUE THREAD

**Issue by emcodem** [m0rtadelo/recursive-readdir-async#27]
Hi and of course thanks for the great module.

Would you mind introducing special character safety by not using strings in fs functions?

The issue starts with: 
`FS.readdir(rpath, function (err, files) {`

Readdir in this case returns a list of strings (utf8? utf16? not sure about it...) but in certain cases of special characters eg. mixed unicode, the string was translated wrongly and stat fails to work with it. 

A safer version is to work with buffers:
`FS.readdir(rpath, {encoding: 'buffer'},function (err, files) {`

This should allow to work with virtually any file that resides on the filesystem, totally independent of their name composition.

**Comment by emcodem** [comment]
Here some example how to generate an affected filename for testing on linux. It contains the character that bugged me (hex 84). Not sure if this is reproduceable on every filesystem and OS, encoding etc... Anyway, using buffers is much more versatile than using strings.

```
var root_path = Buffer.from('/tmp/special_char');
var path_sep = Buffer.from('/');
var fname = Buffer.from('842E747874',"hex");
var fullpath_buf = Buffer.concat([root_path, path_sep, fname]);
console.log("Generating File: ",fullpath_buf .toString());
FS.writeFileSync(fullpath_buf ,"test");
```

**Comment by m0rtadelo** [comment]
Hello,

thank you for your support, i will try to implement your solution.

**Comment by m0rtadelo** [comment]
Added into version 1.3.0
