### ISSUE TITLE
Will there be any typescript support for this?

### ISSUE THREAD

**Issue by pl4yradam** [m0rtadelo/recursive-readdir-async#7]

**Comment by m0rtadelo** [comment]
what do you mean? Importing modules using ES6 import?

**Comment by pl4yradam** [comment]
the error i get using es is:
`ERROR TypeError: Cannot set property 'LIST' of undefined`

Or if i import it like this:
`import * as rra from 'recursive-readdir-async';

And use like: 
```
 const acf = await rra.list(folderName, {
            recursive: false,
            include: ['.exe'],
        });
```

Error is: 
```
ERROR in .<location>
"export 'list' (imported as 'rra') was not found in 'recursive-readdir-async'
```

**Comment by m0rtadelo** [comment]
i will try to add support for ES6 module (now only works with CommonJS and typescript uses ES6 type modules)

**Comment by m0rtadelo** [comment]
version 1.1.8 adds compatibility with ES6 module (using the import key). Module (as rra) can be used with:
`import * as rra from 'recursive-readdir-async'`
